cluster_client:
  network: tcp
  local_ip: 0.0.0.0
  tls_cert_file: ""
  tls_key_file: ""
  default_session_age: 0s
  default_context_age: 0s
  default_dial_timeout: 0s
  failover: 0
  slow_comet_duration: 0s
  default_body_codec: ""
  print_detail: false
  count_time: false
  heartbeat_second: 0
  circuit_breaker:
    enable: false
    error_percentage: 50
    break_duration: 5s

etcd:
  endpoints:
  - http://127.0.0.1:2379
  dial_timeout: 15s
  username: ""
  password: ""

gateway:
  gw:
    enable_http: true
    enable_socket: true
    outer_http_server:
      listen_address: 0.0.0.0:5000
      outer_host: ""
      tls_cert_file: ""
      tls_key_file: ""
      allow_cross: true
    outer_socket_server:
      network: ""
      listen_address: 0.0.0.0:5020
      tls_cert_file: ""
      tls_key_file: ""
      default_session_age: 0s
      default_context_age: 0s
      slow_comet_duration: 0s
      default_body_codec: ""
      print_detail: true
      count_time: true
      enable_heartbeat: true
    inner_socket_server:
      network: ""
      listen_address: 0.0.0.0:5030
      tls_cert_file: ""
      tls_key_file: ""
      default_session_age: 0s
      default_context_age: 0s
      slow_comet_duration: 0s
      default_body_codec: ""
      print_detail: true
      count_time: true
      enable_heartbeat: true
  gray_socket_client:
    network: ""
    local_ip: ""
    tls_cert_file: ""
    tls_key_file: ""
    default_session_age: 0s
    default_context_age: 0s
    default_dial_timeout: 0s
    failover: 3
    slow_comet_duration: 0s
    default_body_codec: ""
    print_detail: false
    count_time: false
    heartbeat_second: 60
    circuit_breaker:
      enable: false
      error_percentage: 0
      break_duration: 0s
  gray_etcd:
    endpoints:
    - http://127.0.0.1:2379
    dial_timeout: 0s
    username: ""
    password: ""
  redis:
    deploy_type: single
    for_single:
      addr: 127.0.0.1:6379
    for_cluster:
      addrs: []
    pool_size_per_node: 0
    idle_timeout: 0
  mysql:
    database: test
    username: root
    password: ""
    host: 127.0.0.1
    port: 3306
    max_idle_conns: 0
    max_open_conns: 0
    conn_max_lifetime: 0
    no_cache: false

server:
  etcd:
    dial_timeout: 0s
    endpoints:
    - http://127.0.0.1:2379
    password: ""
    username: ""
  redis:
    deploy_type: single
    for_cluster:
      addrs: []
    for_single:
      addr: 127.0.0.1:6379
    idle_timeout: 0
    pool_size_per_node: 0
  srv:
    count_time: false
    default_body_codec: ""
    default_context_age: 0s
    default_session_age: 0s
    enable_heartbeat: true
    listen_address: :0
    network: ""
    print_detail: false
    slow_comet_duration: 0s
    tls_cert_file: ""
    tls_key_file: ""
